# Generated by Django 4.2.16 on 2025-10-31 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=50)),
                ('parameters', models.JSONField()),
                ('data', models.JSONField()),
                ('file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_generating', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Report Cache',
                'verbose_name_plural': 'Report Caches',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['report_type', '-created_at'], name='analytics_r_report__8945e9_idx'), models.Index(fields=['expires_at'], name='analytics_r_expires_c21d36_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyRequestStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_requests', models.IntegerField(default=0)),
                ('fulfilled_requests', models.IntegerField(default=0)),
                ('pending_requests', models.IntegerField(default=0)),
                ('cancelled_requests', models.IntegerField(default=0)),
                ('blood_type_breakdown', models.JSONField(default=dict)),
                ('urgency_breakdown', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Request Statistics',
                'verbose_name_plural': 'Daily Request Statistics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['-date'], name='analytics_d_date_d98c14_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyInventorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('inventory_levels', models.JSONField(default=dict)),
                ('expiring_soon', models.JSONField(default=dict)),
                ('expired_today', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Inventory Snapshot',
                'verbose_name_plural': 'Daily Inventory Snapshots',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['-date'], name='analytics_d_date_ce3681_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyDonationStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_donations', models.IntegerField(default=0)),
                ('successful_donations', models.IntegerField(default=0)),
                ('rejected_donations', models.IntegerField(default=0)),
                ('blood_type_breakdown', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Donation Statistics',
                'verbose_name_plural': 'Daily Donation Statistics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['-date'], name='analytics_d_date_075eee_idx')],
            },
        ),
    ]
